FROM mcr.microsoft.com/vscode/devcontainers/universal:1-linux

RUN whoami
RUN pwd
RUN ls -ld
RUN wget https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip
RUN unzip terraform_1.0.2_linux_amd64.zip
